### ISSUE TITLE
Missing Operation Bills

### ISSUE THREAD

**Issue by MrXarous** [emipa606/Cyberpunk#1]
Just Harmony/Core/Royalty/Ideology/Biotech/HugsLib/Cyberpunk (Continued)

I could dev mode and spawn in items from the mod but even them allowed in my stockpile a nearby hospital bed a max level surgeon and glitterworld medicine available the operation to add any of the bodyparts such as armoredleg_cp did not show. There was no errors in the log.

**Comment by emipa606** [comment]
This issue seems to have been fixed, at least I cannot replicate it
